# Generated by Django 4.2.5 on 2023-09-12 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmiosfs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['number'], 'verbose_name': 'Ogrenciler', 'verbose_name_plural': 'Student-Ogrenciler'},
        ),
    ]
